import { LandingPageJob } from '../models/LandingPageJob';

export class LoftyIntegrationService {
  /**
   * Generates a skeleton for a Lofty CRM landing page payload.
   * Injects environment-configured tracking IDs automatically.
   *
   * @param listingId The internal identifier for the listing job.
   * @param address The property address.
   * @param imageUrl The URL or path to the hero image generated by Magnific.
   * @param highlights Property highlights to include in the landing page body.
   * @returns A promise resolving to a LandingPageJob object.
   */
  public static async createOrUpdateLandingPage(
    listingId: string,
    address: string,
    imageUrl: string,
    highlights: string[]
  ): Promise<LandingPageJob> {

    // In a real implementation, this would construct an HTTP POST request
    // to the Lofty CRM API using process.env.LOFTY_API_KEY.

    // Validate we have a key (for logging/mocking purposes)
    const hasApiKey = !!process.env.LOFTY_API_KEY;

    // Retrieve default tracking from env or use fallbacks if env is empty
    const analyticsId = process.env.DEFAULT_GOOGLE_ANALYTICS_ID || 'G-DEFAULT';
    const pixelId = process.env.DEFAULT_FACEBOOK_PIXEL_ID || 'FB-DEFAULT';
    const popupDelay = 7; // Specified in original requirements

    // Generate a mock URL based on address
    const cleanAddress = address.replace(/[^a-z0-9]/gi, '-').toLowerCase();
    const mockPageUrl = `https://crm.lofty.com/landing/${cleanAddress}`;

    const job: LandingPageJob = {
      id: `lofty-job-${Date.now()}`,
      listingId,
      platform: 'Lofty',
      ...(hasApiKey && { pageUrl: mockPageUrl }), // Only provide a URL if API exists
      analyticsId,
      pixelId,
      popupDelaySeconds: popupDelay,
      publishStatus: hasApiKey ? 'Published' : 'Pending',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return job;
  }
}
