import { LandingPageJob } from '../models/LandingPageJob';
import axios from 'axios';

export class LoftyIntegrationService {
  /**
   * Generates a CRM landing page payload.
   * Injects environment-configured tracking IDs automatically.
   * Executes a live HTTP POST if LOFTY_API_KEY is available in the environment.
   *
   * @param listingId The internal identifier for the listing job.
   * @param address The property address.
   * @param imageUrl The URL or path to the hero image generated by Magnific.
   * @param highlights Property highlights to include in the landing page body.
   * @returns A promise resolving to a LandingPageJob object.
   */
  public static async createOrUpdateLandingPage(
    listingId: string,
    address: string,
    imageUrl: string,
    highlights: string[]
  ): Promise<LandingPageJob> {
    const apiKey = process.env.LOFTY_API_KEY;

    const analyticsId = process.env.DEFAULT_GOOGLE_ANALYTICS_ID || 'G-DEFAULT';
    const pixelId = process.env.DEFAULT_FACEBOOK_PIXEL_ID || 'FB-DEFAULT';
    const popupDelay = 7;

    const cleanAddress = address.replace(/[^a-z0-9]/gi, '-').toLowerCase();
    let publishedUrl: string | undefined = undefined;
    let finalStatus: LandingPageJob['publishStatus'] = 'Pending';

    if (apiKey) {
      try {
        // Execute live CRM payload
        const response = await axios.post(
          'https://api.lofty.com/v1/landing-pages',
          {
            title: address,
            hero_image: imageUrl,
            property_features: highlights,
            tracking: {
              google_analytics_id: analyticsId,
              facebook_pixel_id: pixelId,
              popup_delay: popupDelay
            }
          },
          {
            headers: {
              'Authorization': `Bearer ${apiKey}`,
              'Content-Type': 'application/json'
            }
          }
        );

        if (response.data && response.data.url) {
          publishedUrl = response.data.url;
          finalStatus = 'Published';
        } else {
          finalStatus = 'Failed';
        }
      } catch (error) {
        finalStatus = 'Failed';
      }
    } else {
      // Fallback local mock behavior
      publishedUrl = `https://crm.lofty.com/landing/${cleanAddress}`;
      finalStatus = 'Pending'; // Mock implies we are waiting for real tokens
    }

    return {
      id: `lofty-job-${Date.now()}`,
      listingId,
      platform: 'Lofty',
      ...(publishedUrl && finalStatus === 'Published' && { pageUrl: publishedUrl }),
      analyticsId,
      pixelId,
      popupDelaySeconds: popupDelay,
      publishStatus: finalStatus,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }
}
